// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"finawise.app/server/models"
	"finawise.app/server/models/types"
)

type CreateAccount struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Fullname string `json:"fullname"`
}

type CreateCategory struct {
	Type models.TxnType `json:"type"`
	Name string         `json:"name"`
}

type CreateTransaction struct {
	CID       types.ID        `json:"cid"`
	Amount    float64         `json:"amount"`
	Timestamp types.Timestamp `json:"timestamp"`
	Title     string          `json:"title"`
}

type Mutation struct {
}

type Query struct {
}
