// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"finawise.app/server/models"
	"finawise.app/server/models/types"
)

type CreateAccount struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Fullname string `json:"fullname"`
}

type CreateBudget struct {
	CategoryID types.ID `json:"cid"`
	Amount     float64  `json:"amount"`
}

type CreateCategory struct {
	Name  string              `json:"name"`
	Type  models.CategoryType `json:"type"`
	Emoji string              `json:"emoji"`
	Color string              `json:"color"`
}

type CreateTransaction struct {
	CategoryID types.ID        `json:"cid"`
	Title      string          `json:"title"`
	Amount     float64         `json:"amount"`
	Timestamp  types.Timestamp `json:"timestamp"`
}

type Mutation struct {
}

type Query struct {
}
