package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.71

import (
	"context"

	"finawise.app/server/models"
	"finawise.app/server/models/types"
	"finawise.app/server/services/account"
)

// Group is the resolver for the group field.
func (r *accountResolver) Group(ctx context.Context, obj *models.Account) (models.Group, error) {
	return r.Repository.GetGroup(obj.GroupID)
}

// Summary is the resolver for the summary field.
func (r *accountResolver) Summary(ctx context.Context, obj *models.Account) (models.AccountSummary, error) {
	return r.Repository.GetAccountSummary(obj.ID)
}

// Group is the resolver for the group field.
func (r *categoryResolver) Group(ctx context.Context, obj *models.Category) (models.Group, error) {
	return r.Repository.GetGroup(obj.GroupID)
}

// Transactions is the resolver for the transactions field.
func (r *categoryResolver) Transactions(ctx context.Context, obj *models.Category) ([]models.Transaction, error) {
	session := ctx.Value("session").(account.Session)
	return r.Repository.ListTransactions(session.AccountID, &obj.ID, nil)
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, a CreateAccount) (int64, error) {
	return r.AccountService.Register(a.Email, a.Password, a.Fullname)
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, c CreateCategory) (types.ID, error) {
	session := ctx.Value("session").(account.Session)
	return r.Repository.CreateCategory(models.Category{
		GroupID: session.GroupID,
		Name:    c.Name,
		Type:    c.Type,
	})
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, t CreateTransaction) (types.ID, error) {
	session := ctx.Value("session").(account.Session)
	return r.Repository.CreateTransaction(models.Transaction{
		AccountID:  session.AccountID,
		CategoryID: t.CID,
		Amount:     t.Amount,
		Time:       t.Time,
		Title:      t.Title,
		Note:       t.Note,
	})
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context) (models.Account, error) {
	session := ctx.Value("session").(account.Session)
	return r.Repository.GetAccount(session.AccountID)
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id types.ID) (models.Category, error) {
	return r.Repository.GetCategory(id)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, tt *models.TxnType) ([]models.Category, error) {
	session := ctx.Value("session").(account.Session)
	return r.Repository.GetCategories(session.GroupID, tt)
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, id types.ID) (models.Transaction, error) {
	return r.Repository.GetTransaction(id)
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, tt *models.TxnType) ([]models.Transaction, error) {
	session := ctx.Value("session").(account.Session)
	return r.Repository.ListTransactions(session.AccountID, nil, tt)
}

// Account is the resolver for the account field.
func (r *transactionResolver) Account(ctx context.Context, obj *models.Transaction) (models.Account, error) {
	return r.Repository.GetAccount(obj.AccountID)
}

// Category is the resolver for the category field.
func (r *transactionResolver) Category(ctx context.Context, obj *models.Transaction) (models.Category, error) {
	return r.Repository.GetCategory(obj.CategoryID)
}

// Account returns AccountResolver implementation.
func (r *Resolver) Account() AccountResolver { return &accountResolver{r} }

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Transaction returns TransactionResolver implementation.
func (r *Resolver) Transaction() TransactionResolver { return &transactionResolver{r} }

type accountResolver struct{ *Resolver }
type categoryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type transactionResolver struct{ *Resolver }
